nix-community/nh

src/home.rs, src/interface.rs, src/nixos.rs
Adds `--update` so the flake inputs are bumped before the rebuild. The current implementation puts the update command *after* the --dry check, so the user will see the diff before they update the system.
=> add --update flag to bump flake inputs before rebuild

module.nix
When using the nixos module in a system that defines `system` via `nixpkgs.hostPlatform`, evaluation fails with the following error:
```
error: Neither nixpkgs.system nor any other option in nixpkgs.* is meant
to be read by modules and configurations.
Use pkgs.stdenv.hostPlatform instead.
```
See a minimal reproduction flake in [this gist](https://gist.github.com/mrene/4cd68bde1af93f959f2587ae0facbe11)
Eval with: 
```
nix eval git+https://gist.github.com/4cd68bde1af93f959f2587ae0facbe11.git#nixosConfigurations.test.config.system.build.toplevel
```
=> Fix evaluation errors in nixos module

Cargo.lock, Cargo.toml, src/home.rs, src/nixos.rs, src/search.rs
The current iteration of the `--update` flag is missing `--flake` as described by `nix flake update --help`. This MR adds it (big surprise.)
Currently a draft because I'd like to implement a version gate for those below v2.19 instead of failing spectacularly.
=> fix --update on newer nix versions

src/nixos.rs
The new behaviour is consistent with "nixos-rebuild test". The nix-profile is only set on "boot" and "switch".
In the old implementation, builds with "nh os test" were later added to the boot menu on "nh os switch".
Fixes #81.
=> fix: "nh os test" do not set nix-profile

README.md
=> docs: `nix-output-manager` should be `nix-output-monitor`

README.md
the example didn't work because it was missing the beginning of the curly bracket
=> added start curly bracket

src/search.rs
Fixes a weird case where `nh search <package>` would hang indefinitely.
=> fix indefinite hang on nh search

src/clean.rs, src/home.rs, src/nixos.rs
This change exits the program with code 1 when the user rejects changing to the new configuration. The motivation behind this change is to make it easier to wrap this program in scripts.
As i have written in the code, i wanted to propagate the error properly but with color_eyre this doesn't seem to be an option.
I was also a bit confused what `drop(out_dir)` was doing there and couldn't understand the comment, so i changed it to something more clear.
=> Return with exit code when --ask is not accepted

src/interface.rs, src/main.rs, src/nixos.rs, src/repl.rs
Adds a generic implementation of a `nix repl` wrapper, and a repl subcommand for `nh os` which puts the user into a repl with the active nixosConfiguration. Equivalent of `nix repl .#nixosConfiguration.$HOSTNAME` or entering nix repl and running `:lf nixosConfigurations.<hostname>`.
home repl is not implemented because 1. I conceptually disagree with standalone home-manager and 2. it would depend on functions defined in home.rs, which I would rather not pass around haphazardly - might be implemented properly when there is a more standard library/utility module in nh's codebase.
=> nh os repl: init

shell.nix
Allows building nh with `cargo build` on darwin. Without this change, you get errors such as
```bash
note: ld: library not found for -liconv
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
when building on darwin with nix devshell.
=> Dev: add darwin build deps

.github/workflows/build.yaml, src/clean.rs, src/commands.rs, src/darwin.rs
Solves #182, I've also addressed a bug that I forgot about when I first implemented the darwin functionality involving how sudo behaves on mac.
The macos runners for github actions use minutes at 10x the rate of linux runners, and the version doesn't effect it, so I went for latest.
=> Test switching to darwin configuration

src/darwin.rs, src/nixos.rs
fix #191
have tested the `-o` function.
=> fix: do not generated `result`  in pwd without `-o` args

Cargo.lock, Cargo.toml, src/generations.rs, src/interface.rs, src/main.rs, src/nixos.rs
Quick and dirty implementation for `nh os info`, which would list
- Information for current generation
- Rest of the generations (if any) in a formatted table
when executed. WIP, I'll be working on this once I have some more time. Feedback welcome.
Closes #198
=> nh os info

README.md, src/home.rs, src/interface.rs
resolved merge conflicts for #109
=> support for standalone home specialisation

src/interface.rs, src/search.rs
A common use case, for me, is to find what platforms are supported by a package in nixpkgs. This returns those results in the search command. Not sure if you would rather this be gated behind a flag.
=> search.rs: include platforms in search results

src/darwin.rs, src/home.rs, src/nixos.rs, src/util.rs
=> fix: get hostname consistently

src/darwin.rs, src/home.rs, src/installable.rs, src/interface.rs, src/main.rs, src/nixos.rs
Changes as discussed with @viperML on Discord.
Makes nh aware of `NH_OS_FLAKE`, `NH_HOME_FLAKE`, and `NH_DARWIN_FLAKE` variables to override `NH_FLAKE` variable per-command, and includes some typo fixes within the code.
Tested for `os` and `home` subcommands, but I don't have a Darwin machine to test with. Override works as intended.
Supersedes #235
=> make nh commands aware of NH_*_FLAKE

Cargo.lock, flake.lock, flake.nix
Update to NixOS 24.11 (which is the current stable) from NixOS 24.05. Our cargo version is already outdated, and it errors when dependencies are updated.
=> build: bump deps

CHANGELOG.md, Cargo.lock, Cargo.toml, src/interface.rs, src/search.rs
Passing `--json`, or defining `NH_SEARCH_JSON`, will now output search results in the JSON format.
=> search: allow returning output in JSON format

src/commands.rs, src/main.rs
A GUI based popup seems more "intuitive" when calling `sudo` internally, as the application just asking for password with sudo on terminal "feels" like hijacking the program. Ofcourse that is not the case, it is completely personal opinion, but you may want to consider this.
Also for those with `sudo` enabled with fingerprint access, it is much more difficult to deal with terminal, as default configuration makes you go for "three fingerprint attempts" before it asks you for password. So if you do not want to use fingerprint, but password instead, normally for programs running with `sudo` (say `sudo echo hello`), you can just <kbd>Ctrl</kbd>+<kbd>C</kbd> during the first attempt, and then password input appears. But since `nh` calls it internally, <kbd>Ctrl</kbd>+<kbd>C</kbd> just halts …
=> use SUDO_ASKPASS program if set

CHANGELOG.md, Cargo.lock, Cargo.toml, src/home.rs
This is a little dirty for my taste, but it fixes the regression inbetween 3.6.0 and the 4.0.0 releases. Not sure where the regression was introduced, but from what I can tell the latest 4.0.0 beta does not have the logic to parse `--configuration` so it's definitely @viperML's fault and not mine. Trust :pray:
I've also made home switch a little more verbose and improved existing implementation where it caught my attention.
Fixes #262
=> home: ensure `--configuration` is correctly passed to switch

README.md, package.nix, src/logging.rs
nh has moved to nix-community, let all links reflect that.
=> chore: fix links

CHANGELOG.md, src/darwin.rs
Closes https://github.com/viperML/nh/issues/233
Basically, with the new nix-darwin rewrite everything is moved to root activation. I check if the nix-darwin user activation script contains the deprecation notice. ~If it does, we just call the activate script only. (Where the old user activation stuff has been moved)~ Also, moved to using the `darwin-rebuild` script instead of the activation scripts directly so that `nix-darwin` can handle migrations themselves and we don't have to worry about the current implementation details every time a change is made upstream. We just elevate the `activate` when it needs to be. 
Marking draft until the deprecation marker is solidified in https://github.com/LnL7/nix-darwin/pull/1341
=> darwin.rs: handle new root only activation

CHANGELOG.md, src/commands.rs, src/interface.rs, src/nixos.rs, src/util.rs
part of #254
not sure if the right move here is to invoke `ln -s` over ssh to make sure the out_path is symlinked correctly on the target machine, or if just canonicalize'ing the paths is the right move, i went for canonicalize just because it felt less hacky than invoking `ln -s` over ssh
it currently works for me on my own local server
=> nixos: add `--target-host` and `--build-host` options

CHANGELOG.md, src/generations.rs, src/interface.rs, src/nixos.rs
Implement `nh os rollback`. This is implemented as a subcommand and not a flag, because I do not want to parse different cli flag combinations on top of `nh os switch`.
Closes #30
=> nixos: implement rollbacks

.github/workflows/build.yaml, .github/workflows/check.yaml, Cargo.toml, fix.sh, src/clean.rs, src/commands.rs, src/completion.rs, src/darwin.rs, src/generations.rs, src/home.rs, src/installable.rs, src/interface.rs, src/json.rs, src/logging.rs, src/nixos.rs, src/update.rs
Refactors and cleans up existing CI and related files. The fix script now runs more clippy lints, which are also checked in the lints CI that I have isolated from the build workflow.
This should be merged *after* we close incoming contribution PRs, as it __reformats the entire source tree__ and will cause many, *many* merge conflicts.
=> CI: refactor

src/main.rs
Closes #289
Some environment variables such as `NH_NO_CHECKS` modify the behaviour of commands that require elevated privileges such as `nh clean all`. This fix allows all environment variables to be preserved after the call to `self_elevate()`.
=> fix: preserve environment variables after self_elevate()

fix.sh
Running `./fix.sh` errors with
```sh
+ echo 'Running clippy linter and applying available fixes'
Running clippy linter and applying available fixes
+ cargo clippy --fix --allow-dirty -W clippy::pedantic -W clippy::pedantic -W clippy::correctness -W clippy::suspicious
error: unexpected argument '-W' found
```
This fixes it and removes a duplicate line.
=> fix cargo clippy command in fix.sh

CHANGELOG.md, src/checks.rs
As the latest lix release has removed the repl-flake feature, we can't demand it on that version anymore.
This fixes #278. (I tested by overriding nixpkgs' nh package with the patch from this PR.)
=> Disable check for repl-flake on lix>=2.93

src/commands.rs, src/darwin.rs, src/generations.rs, src/home.rs, src/nixos.rs
This'll create some merge conflicts, but I'd like to get this fixed before I take an extended break. Fixes nvd diffs and supresses a redundant argument that would occur after #208. Also improves debug logging for references that we need to keep track of. Should help track down issues such as this one easier in the future.
CC @khaneliman for Darwin testing, seems to be working as intended on NixOS- testing for Home Manager would also be great.
=> treewide: fix nvd diffs and internal cleanup

src/main.rs
Fixes https://github.com/nix-community/nh/issues/202
Tested manually full works!
=> fix: self eval passwd warning for darwin

package.nix, shell.nix
Deprecated, in stdenv and doesn't need to be there. Throws warning.
=> {package,shell}: remove darwin stubs

Cargo.toml, flake.lock, flake.nix, src/checks.rs, src/clean.rs, src/commands.rs, src/darwin.rs, src/generations.rs, src/home.rs, src/interface.rs, src/json.rs, src/logging.rs, src/nixos.rs, src/search.rs, src/update.rs, src/util.rs
NixOS 25.05 is out, and we're ready to switch. Since there are no user-facing changes, this will not be making it into a new release. We also update to 2024 edition so that integration with [bloxx12/dix](https://github.com/bloxx12/dix) is possible.
This will be merged before #281, and it'll probably cause a lot of merge conflicts. As such I'll probably close 281 and re-open it when I have more free time in my hands.
=> meta: switch to Nixpkgs 25.05; bump Cargo edition

CHANGELOG.md, src/nixos.rs
=> build and build-vm now default to output in ./result

shell.nix, src/commands.rs
Previously running `--no-nom` failed to set `--builders`.
I have also added lldb to the devShell in a second commit and I'm too lazy to open a second PR.
=> Fix issue #308: Ensure `builders` arg is passed to Exec on all branches.

.gitignore, CHANGELOG.md, Cargo.lock, Cargo.toml, src/checks.rs, src/interface.rs, src/main.rs, src/util.rs
Changes Nix environment checks to a trait-based, less monolithic design to avoid redundant feature checks for commands that don't require checked features in the first place. There is a performance impact, but in my experience it is... not noticable as per my testing.
Regardless I think this is more robust in design, and introduces further future-proofing the current implementation is not fully capable of. Also provides groundwork for supporting more Nix variants in the future cleanly, without utility functions to check everything one-by-one.
Fixes #305, #309
Closes #315
=> checks: improve robustness

src/clean.rs
The output of `nix store gc` is just one line showing the number of paths and amount of disk space freed. This information was quite informative and it would be good to have it back.
=> Show output of `nix store gc` in clean

CHANGELOG.md, src/commands.rs, src/main.rs, src/nixos.rs
Safer, cleaner environment handling to fine-grain what is preserved. The goal is to allow specifying similar fine-graining for each command.
Fixes #314
=> commands: better env handling

src/clean.rs, src/commands.rs, src/darwin.rs, src/generations.rs, src/home.rs, src/installable.rs, src/interface.rs, src/json.rs, src/nixos.rs
Ensures that all relevant NH_* variables ara preserved across command invocations. This should allow config-level overrides over variables set internally.
=> treewide: ensure all relevant env vars are preserved; lint

src/commands.rs, src/darwin.rs, src/home.rs, src/interface.rs, src/nixos.rs, src/util/platform.rs
This patch adds support for passing Nix build flags (like --max-jobs, --keep-going, --show-trace, etc.) directly to rebuild commands. A new NixBuildPassthroughArgs struct collects these options and passes them through the CLI to the build logic for Darwin, NixOS, and Home Manager workflows.
The code is based on the [consolidate-logic](https://github.com/nix-community/nh/commits/consolidate-logic). I have cherry picked Andreas Fuchs commit so it runs on the version of Lix I use. Feel free to disregard that and merge it later if easier.
I'm open to feedback about which arguments to actually pass through. Other than `-t` for `--show-trace`, these are all standard. 
Currently I have:
```rust
#[derive(Debug, Args)]
pub struct NixBuildPassthroughArgs {
/// Number of concurrent jobs Nix should …
```
=> Add Nix Build Passthrough Arguments to Rebuild Commands

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/test.yaml, src/commands.rs, test/configuration.nix
Fixes some of the inconsistencies left over in the commands module. This was never harmful, but the removal of leftover "bad" code will help with NH's maintenance in the long run.
1. It makes environment preservation more consistent and intuitive
2. Unifies preservation logic for Linux and Darwin
3. Cleans up code wherever I see it.
I also separated test workflows from build workflows so that we may receive more targeted feedback from the CI. While NixOS VM tests are still a future goal, this appropriately tests NH in a small scope that I find... tolerable.
=> commands: better error propagation & env preservation

src/clean.rs, src/interface.rs
Renames `--nogc` and `--nogcroots` to `--no-gc` and `--no-gcroots` respectively. This is a change in the name of consistency, and should be handled gracefully thanks to Clap's aliases. Though, you are encouraged to update your scripts or aliases in case those are deprecated in the future.
Additionally, `--optimise` and `--max` flags have been introduced. You may use the former to optimise your Nix store right after a GC and the latter to fine-grain `nix store gc`'s behaviour.
Change-Id: I6a6a69648ffe8a8abe759f773f83b1031e137981
=> clean: better interface for commands; passthru `--max`; optimise

Cargo.lock, Cargo.toml, src/clean.rs, src/darwin.rs, src/home.rs, src/nixos.rs, src/util/platform.rs
Better maintained apparently.
This replaces the dialoguer library that we've used for prompting users for confirmation with the [inquire](https://docs.rs/inquire/latest/inquire/) library. Aside from being slightly better maintained, it appears to have solved signal handling issues that dialoguer had.
Change-Id: I6a6a6964ec4608a2840c54bae939c692fd747049
=> treewide: replace dialoguer with inquire
